# Imagen base con Flutter preinstalado
FROM cirrusci/flutter:stable

# Variables de entorno necesarias para Android
ENV ANDROID_HOME=/opt/android-sdk-linux
ENV PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin

# Instalamos el SDK Manager y herramientas necesarias
RUN yes | sdkmanager --licenses \
 && sdkmanager "platform-tools" \
                "platforms;android-33" \
                "build-tools;33.0.2" \
                "ndk;26.3.11579264" \
                "cmdline-tools;latest"

# Aseguramos permisos adecuados
RUN chmod -R a+w $ANDROID_HOME

# Precache y build
WORKDIR /app
COPY . .

RUN flutter precache --web \
 && flutter pub get \
 && flutter build web --release --dart-define=API_URL=http://localhost:8080/api \
 && flutter build apk --release \
 && mkdir -p build/web/apk \
 && cp build/app/outputs/flutter-apk/app-release.apk build/web/apk/
