name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.VPS_USER }}/producapp"
          rm: true

      - name: Run deploy commands on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/producapp

            # Crear secretos Docker si no existen
            echo "${{ secrets.USER_ROOT }}" | docker secret create user_root_database || true
            echo "${{ secrets.PASS_ROOT }}" | docker secret create password_root_database || true
            echo "${{ secrets.USER_DB }}"   | docker secret create user_database_mysql || true
            echo "${{ secrets.PASS_DB }}"   | docker secret create password_database_mysql || true

            # Crear archivo .env
            echo "${{ secrets.ENV_PROD_CONTENT }}" > .env

            # Construir y levantar contenedores
            docker-compose down
            docker-compose pull || true
            docker-compose build || true
            docker-compose up -d --build
