name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: yuliana
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/home/yuliana/app"
          rm: true  # Elimina archivos en destino que ya no están en el repo (opcional)

      - name: Run Docker Compose on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: yuliana
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/yuliana/app
            docker-compose pull || true
            docker-compose build || true
            docker-compose up -d --build
